### ISSUE TITLE
upgrade to v2024.07, salt-secrets-config.service failt to start

### ISSUE THREAD

**Issue by StefanSa** [uyuni-project/uyuni#9105]
### Problem description

Hi there,
After updating from v2024.05 to v2024.07, the salt-secrets-config.service no longer starts.

```
systemctl status salt-secrets-config.service
× salt-secrets-config.service - Configures secrets between salt-master and other services
     Loaded: loaded (/usr/lib/systemd/system/salt-secrets-config.service; static)
    Drop-In: /usr/lib/systemd/system/salt-secrets-config.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Thu 2024-07-25 13:19:00 CEST; 1min 51s ago
    Process: 902 ExecStart=/usr/bin/salt-secrets-config.py (code=exited, status=1/FAILURE)
   Main PID: 902 (code=exited, status=1/FAILURE)

Jul 25 13:18:59 uni-01 systemd[1]: Starting Configures secrets between salt-master and other services...
Jul 25 13:19:00 uni-01 salt-secrets-config.py[902]: Traceback (most recent call last):
Jul 25 13:19:00 uni-01 salt-secrets-config.py[902]:   File "/usr/bin/salt-secrets-config.py", line 15, in <module>
Jul 25 13:19:00 uni-01 salt-secrets-config.py[902]:     from spacewalk.common.rhnConfig import cfg_component
Jul 25 13:19:00 uni-01 salt-secrets-config.py[902]: ImportError: cannot import name 'cfg_component'
Jul 25 13:19:00 uni-01 systemd[1]: salt-secrets-config.service: Main process exited, code=exited, status=1/FAILURE
Jul 25 13:19:00 uni-01 systemd[1]: salt-secrets-config.service: Failed with result 'exit-code'.
Jul 25 13:19:00 uni-01 systemd[1]: Failed to start Configures secrets between salt-master and other services.
```
a `zypper up spacewalk-backend-server` give this here:
```
Repository-Daten werden geladen...
Installierte Pakete werden gelesen...
Paketabhängigkeiten werden aufgelöst...

Problem: 1: das installierte spacewalk-backend-config-files-common-5.0.5-230900.2.5.uyuni3.noarch erfordert 'spacewalk-backend-server = 5.0.5-230900.2.5.uyuni3', aber diese Anforderung kann nicht bereitgestellt werden
Gelöschte Anbieter: spacewalk-backend-server-5.0.5-230900.2.5.uyuni3.noarch

 Lösung 1: Folgende Aktionen werden ausgeführt:
  Deinstallation von spacewalk-backend-config-files-common-5.0.5-230900.2.5.uyuni3.noarch
  Deinstallation von spacewalk-backend-config-files-5.0.5-230900.2.5.uyuni3.noarch
  Deinstallation von spacewalk-backend-config-files-tool-5.0.5-230900.2.5.uyuni3.noarch
 Lösung 2: spacewalk-backend-server-5.0.6-230900.1.4.uyuni3.noarch nicht installieren
 Lösung 3: spacewalk-backend-config-files-common-5.0.5-230900.2.5.uyuni3.noarch durch Ignorieren einiger Abhängigkeiten brechen
````

i have restored the snapshot from this VM, currently v2024.05 is working correctly again.

any help here
Stefan

### Steps to reproduce

zypper ref && zypper up

### Uyuni version

```bash
zypper info Uyuni-Server-release
Repository-Daten werden geladen...
Installierte Pakete werden gelesen...


Informationen zu Paket Uyuni-Server-release:
--------------------------------------------
Repository         : Uyuni Server Stable
Name               : Uyuni-Server-release
Version            : 2024.05-230900.217.1.uyuni3
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level      : Stufe 3
Installierte Größe : 1,4 KiB
Installiert        : Ja
Status             : veraltet (Version 2024.03-230900.214.6.uyuni3 installiert)
Quellpaket         : Uyuni-Server-release-2024.05-230900.217.1.uyuni3.src
Zusammenfassung    : Uyuni Server
Beschreibung       :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by ZsBT** [comment]
Same problem here. Version:

```
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2024.07-230900.219.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
```

**Comment by hsh-it** [comment]
Same here
**uyuni:~ # spacewalk-service stop**
```
e startShutting down spacewalk services...
Done.
```
**uyuni:~ # zypper ref**
```
Repository 'Update repository of openSUSE Backports' is up to date.
Repository 'Non-OSS Repository' is up to date.
Repository 'Haupt-Repository' is up to date.
Repository 'Update repository with updates from SUSE Linux Enterprise 15' is up to date.
Repository 'Quell-Repository' is up to date.
Repository 'Hauptaktualisierungs-Repository' is up to date.
Repository 'Aktualisierungs-Repository (Nicht-Open-Source-Software)' is up to date.
Repository 'Project used to release critical patches between releases (openSUSE_Leap_15.4)' is up to date.
Repository 'uyuni-server-stable' is up to date.
Repository 'Zabbix Official Repository' is up to date.
All repositories have been refreshed.
```
**uyuni:~ # zypper up**
```
Loading repository data...
Reading installed packages...

The following 13 package updates will NOT be installed:
  byte-buddy cobbler spacewalk-backend spacewalk-backend-app spacewalk-backend-iss spacewalk-backend-iss-export spacewalk-backend-package-push-server spacewalk-backend-server
  spacewalk-backend-sql spacewalk-backend-sql-postgresql spacewalk-backend-tools spacewalk-backend-xml-export-libs spacewalk-backend-xmlrpc
Nothing to do.
```
**uyuni:~ # zypper install Uyuni-Server-release**
```
Loading repository data...
Reading installed packages...
'Uyuni-Server-release' is already installed.
No update candidate for 'Uyuni-Server-release-2024.07-230900.219.1.uyuni3.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.
```
**uyuni:~ # spacewalk-service start**
```
Starting spacewalk services...
  Checking DB schema and running DB schema upgrade if needed. This may take a while.
  Call the following command to see progress: journalctl -f -u uyuni-check-database.service
○ uyuni-check-database.service - Uyuni check database
     Loaded: loaded (/usr/lib/systemd/system/uyuni-check-database.service; static)
     Active: inactive (dead) since Fri 2024-07-26 08:43:18 CEST; 12s ago
    Process: 21152 ExecStart=/usr/sbin/spacewalk-startup-helper check-database (code=exited, status=0/SUCCESS)
   Main PID: 21152 (code=exited, status=0/SUCCESS)

Jul 26 08:40:22 uyuni spacewalk-startup-helper[21254]: Searching for start path:  [uyuni-reportdb-schema-5.0.5-230900]
Jul 26 08:40:22 uyuni spacewalk-startup-helper[21254]: Searching for start path:  [uyuni-reportdb-schema-5.0.5]
Jul 26 08:40:22 uyuni spacewalk-startup-helper[21254]: The path: [uyuni-reportdb-schema-5.0.5] -> [uyuni-reportdb-schema-5.0.6]
Jul 26 08:40:22 uyuni spacewalk-startup-helper[21254]: Planning to run schema upgrade with dir '/var/log/spacewalk/reportdb-schema-upgrade/schema-from-20240726-084022'
Jul 26 08:40:22 uyuni spacewalk-startup-helper[21254]: Executing spacewalk-sql, the log is in [/var/log/spacewalk/reportdb-schema-upgrade/schema-from-20240726-084022-to-uyuni-reportdb-schema-5.0.6.log].
Jul 26 08:40:26 uyuni spacewalk-startup-helper[21254]: [289B blob data]
Jul 26 08:40:26 uyuni spacewalk-startup-helper[21254]: The database schema was upgraded to version [uyuni-reportdb-schema-5.0.6-230900.1.8.uyuni3].
Jul 26 08:40:27 uyuni systemd[1]: Finished Uyuni check database.
Jul 26 08:43:18 uyuni systemd[1]: uyuni-check-database.service: Deactivated successfully.
Jul 26 08:43:18 uyuni systemd[1]: Stopped Uyuni check database.
Jul 26 08:43:30 uyuni systemd[1]: Starting Uyuni check database...
FAILED
uyuni:~ #
```
**uyuni:~ # journalctl -xe**
```
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ An ExecStart= process belonging to unit salt-secrets-config.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Jul 26 08:41:14 uyuni systemd[1]: salt-secrets-config.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ The unit salt-secrets-config.service has entered the 'failed' state with result 'exit-code'.
Jul 26 08:41:14 uyuni systemd[1]: Failed to start Configures secrets between salt-master and other services.
░░ Subject: A start job for unit salt-secrets-config.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit salt-secrets-config.service has finished with a failure.
░░
░░ The job identifier is 711809 and the job result is failed.
Jul 26 08:41:14 uyuni systemd[1]: Dependency failed for Spacewalk.
░░ Subject: A start job for unit spacewalk.target has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit spacewalk.target has finished with a failure.
░░
░░ The job identifier is 711683 and the job result is dependency.
```
**uyuni:~ # zypper info Uyuni-Server-release**
```
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2024.07-230900.219.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.07-230900.219.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by digdilem** [comment]
Same here. Can the dev team look at this as a matter of priority please?

This seems to be breaking repo syncs also

Am concerned that this is supposed to be the last traditional release, so is there a plan to release another non-broken update?

> ● salt-secrets-config.service                                                                      loaded failed failed    Configures secrets between salt-master and oth

And cfg_component mentioned in daily repo sync failure error:

```
Command '[/usr/bin/spacewalk-repo-sync, --channel, debian-12-amd64-uyuni-client, --type, deb, --non-interactive]' exited with error code 1: Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 32, in 
    from spacewalk.satellite_tools.syncLib import initEMAIL_LOG
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/syncLib.py", line 33, in 
    from spacewalk.common.rhnLog import log_time, log_clean
  File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnLog.py", line 41, in 
    from uyuni.common.context_managers import cfg_component
  File "/usr/lib/python3.6/site-packages/uyuni/common/context_managers.py", line 8, in 
    from spacewalk.common.rhnConfig import cfg_component
ImportError: cannot import name 'cfg_component'
```

**Comment by digdilem** [comment]
Update: From elsewhere in the issues, forcing the upgrade of a held-back package seems to allow this service to start, and fixes the repo issue. Hopefully the update package will be fixed, so the last traditional release isn't left broken.

` zypper install spacewalk-backend-server`

**Comment by StefanSa** [comment]
@digdilem 
did you also have three suggested solutions like me from zypper, if so which one did you take?

**Comment by digdilem** [comment]
@StefanSa 

Yes - I chose the 1st one when prompted after that. 

A "zypper up" shows several packages that won't install, which leads to this issue and it seems to be affecting quite a few or all people with this upgrade. I saw a deb in one of the issues recommend this. 

After doing the above, most of the conflicts will be resolved - but there are two packages left, including cobbler. Don't be tempted to repeat this on cobbler too, as then cobbler breaks. (I had to roll back to a snapshot)

Everything seems to be working now - at least that service starts, and repo syncing is working again, but It's not a great solution and I hope the devs come out with another fixed traditional release soon.

**Comment by StefanSa** [comment]
@juliogonzalez @mcalmer 
Can either of you help here.
thanks you for your time and uyuni.

**Comment by rjmateus** [comment]
we will have a look. And this is not the last RPM based version that we will be releasing. You should expect two more, 2024.08 and 2024.09.

**Comment by digdilem** [comment]
Thanks for the correction, that's reassuring to know.

**Comment by deneb-alpha** [comment]
hi all,  I can confirm that the zypper solution to drop:

- `spacewalk-backend-config-files-common`
- `spacewalk-backend-config-files`
- `spacewalk-backend-config-files-tool`
It's the right to use.

**Comment by stdevel** [comment]
> hi all, I can confirm that the zypper solution to drop:
> 
>     * `spacewalk-backend-config-files-common`
> 
>     * `spacewalk-backend-config-files`
> 
>     * `spacewalk-backend-config-files-tool`
>       for the moment is the right to use.

Also worked fine for one my machines upgrading from 2024.03 to 2024.07 - thanks for pointing out.

**Comment by hsh-it** [comment]
> Also worked fine for one of my servers upgrading from 2024.03 to 2024.07 - thanks for pointing out.

Danke für das Feedback

**Comment by wizonet** [comment]
Just updated from 2024.05 to 2024.08 - running in the same issue. Uyuni is not working an the webservice acces is dead (404)...

I have now been successful with the following procedure:

snapper rollback to a version before the update.

zypper ref
zypper up

After updating and before reboot:
systemctl start uyuni-check-database.service
spacewalk-service start

reboot

zypper install spacewalk-backend-server
-> Option 1

zypper in spacewalk-java
-> Option 1
-> Overwrite jar files: yes (default is no)

zypper in Uyuni-Server-release

Now uyuni works - but there are some more updates:

uyuni:~ # zypper up
Loading repository data...
Reading installed packages...

The following 19 package updates will NOT be installed:
  apache-commons-ognl classmate cobbler concurrentlinkedhashmap-lru dom4j glassfish-activation-api glassfish-fastinfoset glassfish-jaxb-api
  glassfish-jaxb-runtime glassfish-jaxb-txw2 guava istack-commons-runtime jandex mybatis objectweb-asm reprepro stax-ex xmlstreambuffer xsom
Nothing to do.

I will not install any of these packages for the time being...

**Comment by mcalmer** [comment]
We support now only containerized uyuni where these problems cannot happening anymore. Closing
