### ISSUE TITLE
ImportError: cannot import name 'cfg_component' after Update to 2024.07

### ISSUE THREAD

**Issue by ckguenther** [uyuni-project/uyuni#9097]
### Problem description

Did an update (legacy) from 2024.05 to 2024.07 with the steps for a minor upgrade.

After the upgrade I had the problem that:
1. service salt-secrets-config.service isn't starting anymore
2. spacewalk-common-channels is throwing an error

Both problems seems related as it's the same error message:

uyuni:~ # systemctl status salt-secrets-config.service
Ã— salt-secrets-config.service - Configures secrets between salt-master and other services
     Loaded: loaded (/usr/lib/systemd/system/salt-secrets-config.service; static)
    Drop-In: /usr/lib/systemd/system/salt-secrets-config.service.d
             â””â”€override.conf
     Active: failed (Result: exit-code) since Tue 2024-07-23 07:42:32 CEST; 4min 57s ago
   Main PID: 904 (code=exited, status=1/FAILURE)

Jul 23 07:42:31 uyuni systemd[1]: Starting Configures secrets between salt-master and other services...
Jul 23 07:42:32 uyuni salt-secrets-config.py[904]: Traceback (most recent call last):
Jul 23 07:42:32 uyuni salt-secrets-config.py[904]:   File "/usr/bin/salt-secrets-config.py", line 15, in <module>
Jul 23 07:42:32 uyuni salt-secrets-config.py[904]:     from spacewalk.common.rhnConfig import cfg_component
Jul 23 07:42:32 uyuni salt-secrets-config.py[904]: ImportError: cannot import name 'cfg_component'
Jul 23 07:42:32 uyuni systemd[1]: salt-secrets-config.service: Main process exited, code=exited, status=1/FAILURE
Jul 23 07:42:32 uyuni systemd[1]: salt-secrets-config.service: Failed with result 'exit-code'.
Jul 23 07:42:32 uyuni systemd[1]: Failed to start Configures secrets between salt-master and other services.

uyuni:~ # systemctl status salt-secrets-config.service
Ã— salt-secrets-config.service - Configures secrets between salt-master and other services
     Loaded: loaded (/usr/lib/systemd/system/salt-secrets-config.service; static)
    Drop-In: /usr/lib/systemd/system/salt-secrets-config.service.d
             â””â”€override.conf
     Active: failed (Result: exit-code) since Tue 2024-07-23 07:42:32 CEST; 4min 57s ago
   Main PID: 904 (code=exited, status=1/FAILURE)

Jul 23 07:42:31 uyuni systemd[1]: Starting Configures secrets between salt-master and other services...
Jul 23 07:42:32 uyuni salt-secrets-config.py[904]: Traceback (most recent call last):
Jul 23 07:42:32 uyuni salt-secrets-config.py[904]:   File "/usr/bin/salt-secrets-config.py", line 15, in <module>
Jul 23 07:42:32 uyuni salt-secrets-config.py[904]:     from spacewalk.common.rhnConfig import cfg_component
Jul 23 07:42:32 uyuni salt-secrets-config.py[904]: ImportError: cannot import name 'cfg_component'
Jul 23 07:42:32 uyuni systemd[1]: salt-secrets-config.service: Main process exited, code=exited, status=1/FAILURE
Jul 23 07:42:32 uyuni systemd[1]: salt-secrets-config.service: Failed with result 'exit-code'.
Jul 23 07:42:32 uyuni systemd[1]: Failed to start Configures secrets between salt-master and other services.

After that I switched back to the old version (via snapshot of vm)

### Steps to reproduce

Upgrade from 2024.05 to 2024.07 with following steps:
1. spacewalk-service stop
2. zypper ref
3. zypper up
4. spacewalk-service start
5. wait some minutes
6. systemctl status uyuni-check-database.service
â— uyuni-check-database.service - Uyuni check database
     Loaded: loaded (/usr/lib/systemd/system/uyuni-check-database.service; static)
     Active: active (exited) since Wed 2024-07-24 10:45:27 CEST; 1min 54s ago
    Process: 25670 ExecStart=/usr/sbin/spacewalk-startup-helper check-database (code=exited, status=0/SUCCESS)
   Main PID: 25670 (code=exited, status=0/SUCCESS)

Jul 24 10:45:25 uyuni systemd[1]: Starting Uyuni check database...
Jul 24 10:45:26 uyuni spacewalk-startup-helper[25683]: report_db_host = uyuni.campus.gendorf.net
Jul 24 10:45:26 uyuni spacewalk-startup-helper[25698]: Your database schema already matches the schema package version [susemanager-schema-5.0.10-230900.1.2.uyuni3].
Jul 24 10:45:26 uyuni spacewalk-startup-helper[25698]: Schema upgrade: [susemanager-schema-5.0.10-230900.1.2.uyuni3] -> [susemanager-schema-5.0.10-230900.1.2.uyuni3]
Jul 24 10:45:27 uyuni spacewalk-startup-helper[25726]: Your database schema already matches the schema package version [uyuni-reportdb-schema-5.0.6-230900.1.8.uyuni3].
Jul 24 10:45:27 uyuni spacewalk-startup-helper[25726]: Schema upgrade: [uyuni-reportdb-schema-5.0.6-230900.1.8.uyuni3] -> [uyuni-reportdb-schema-5.0.6-230900.1.8.uyuni3]
Jul 24 10:45:27 uyuni systemd[1]: Finished Uyuni check database.

7. again spacewalk-service start
8. wait again and reboot

After that the service salt-secrets-config.service isn't running and spacewalk-common-channels raises an error - bith with same error
...

### Uyuni version

```bash
uyuni:~ # zypper info Uyuni-server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.07-230900.219.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : out-of-date (version 2024.05-230900.217.1.uyuni3 installed)
Source package : Uyuni-Server-release-2024.07-230900.219.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by ckguenther** [comment]
yes, same issue.
After updating spacewalk-backend  everything is working without any problems.

Thanks for quich response and help.
