### ISSUE TITLE
ImportError: cannot import name 'cfg_component'

### ISSUE THREAD

**Issue by SvenC56** [uyuni-project/uyuni#9092]
### Problem description

After the migration to 2024.07 I cannot sync the software channels anymore:

```
Command '[/usr/bin/spacewalk-repo-sync, --channel, ubuntu-2204-amd64-main-uyuni, --type, deb, --non-interactive]' exited with error code 1: Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 32, in 
    from spacewalk.satellite_tools.syncLib import initEMAIL_LOG
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/syncLib.py", line 33, in 
    from spacewalk.common.rhnLog import log_time, log_clean
  File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnLog.py", line 41, in 
    from uyuni.common.context_managers import cfg_component
  File "/usr/lib/python3.6/site-packages/uyuni/common/context_managers.py", line 8, in 
    from spacewalk.common.rhnConfig import cfg_component
ImportError: cannot import name 'cfg_component'
```

I get this error on any channel on any distribution

### Steps to reproduce

1. Update to 2024.07
2. Sync Channel

### Uyuni version

```bash
Informationen zu Paket Uyuni-Server-release:
--------------------------------------------
Repository         : uyuni-server-stable
Name               : Uyuni-Server-release
Version            : 2024.07-230900.219.1.uyuni3
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level      : Stufe 3
Installierte Größe : 1.4 KiB
Installiert        : Ja
Status             : aktuell
Quellpaket         : Uyuni-Server-release-2024.07-230900.219.1.uyuni3.src
Upstream-URL       : https://www.uyuni-project.org/
Zusammenfassung    : Uyuni Server
Beschreibung       : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
from `/var/log/rhn/rhn_taskomatic_daemon.log`


2024-07-24 09:01:13,876 [DefaultQuartzScheduler_Worker-26] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Unable to sync channel 300
org.quartz.JobExecutionException: Command '[/usr/bin/spacewalk-repo-sync, --channel, ubuntu-22.04-pool-amd64-uyuni, --type, deb, --non-interactive]' exited with error code 1: Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 32, in <module>
    from spacewalk.satellite_tools.syncLib import initEMAIL_LOG
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/syncLib.py", line 33, in <module>
    from spacewalk.common.rhnLog import log_time, log_clean
  File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnLog.py", line 41, in <module>
    from uyuni.common.context_managers import cfg_component
  File "/usr/lib/python3.6/site-packages/uyuni/common/context_managers.py", line 8, in <module>
    from spacewalk.common.rhnConfig import cfg_component
ImportError: cannot import name 'cfg_component'

	at com.redhat.rhn.taskomatic.task.RhnJavaJob.executeExtCmd(RhnJavaJob.java:86) ~[rhn.jar:?]
	at com.redhat.rhn.taskomatic.task.RhnJavaJob.executeExtCmd(RhnJavaJob.java:91) ~[rhn.jar:?]
	at com.redhat.rhn.taskomatic.task.RepoSyncTask.execute(RepoSyncTask.java:110) ~[rhn.jar:?]
	at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:56) ~[rhn.jar:?]
	at com.redhat.rhn.taskomatic.TaskoJob.doExecute(TaskoJob.java:240) ~[rhn.jar:?]
	at com.redhat.rhn.taskomatic.TaskoJob.runTemplate(TaskoJob.java:193) ~[rhn.jar:?]
	at com.redhat.rhn.taskomatic.TaskoJob.execute(TaskoJob.java:145) ~[rhn.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.0.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.0.jar:?]
```
### Additional information

`/usr/lib/python3.6/site-packages/uyuni/common/context_managers.py`

```
"""Collection of context managers for Uyuni."""

# This module always had a dependency on spacewalk.common.rhnConfig, which is wrong.
# Everything in uyuni.common should work on clients as well. When we add other context
# managers (that are available on clients), this import should be guarded.
# Re-export to allow users to keep their import on uyuni.common.context_managers
# pylint: disable-next=unused-import
from spacewalk.common.rhnConfig import cfg_component

```

**Comment by SvenC56** [comment]
Turns out I had an issue updating `spacewalk-backend-server`. After resolving the issue manually the issue now gone.
Ref: https://github.com/uyuni-project/uyuni/issues/8780
