### ISSUE TITLE
mgr-websockify service does not start. Referencing missing JWTTokenApi

### ISSUE THREAD

**Issue by rpasche** [uyuni-project/uyuni#796]
On Leap15.0, running Uyuni Server, the service ```mgr-websockify``` does not start. It references a missing module / class ```JWTTokenApi```. This should be included in package ```python3-websockify-0.8.0```, but the ```token_plugin.py``` file is missing the requested class.

```
Apr 03 16:46:47 uyuni-test systemd[1]: Starting TCP to WebSocket proxy...
Apr 03 16:46:48 uyuni-test systemd[1]: Started TCP to WebSocket proxy.
Apr 03 16:46:49 uyuni-test websockify[1011]: Traceback (most recent call last):
Apr 03 16:46:49 uyuni-test websockify[1011]:   File "/usr/bin/websockify", line 11, in <module>
Apr 03 16:46:49 uyuni-test websockify[1011]:     load_entry_point('websockify==0.8.0', 'console_scripts', 'websockify')()
Apr 03 16:46:49 uyuni-test websockify[1011]:   File "/usr/lib/python3.6/site-packages/websockify/websocketproxy.py", line 511, in websockify_init
Apr 03 16:46:49 uyuni-test websockify[1011]:     token_plugin_cls = getattr(sys.modules[token_plugin_module], token_plugin_cls)
Apr 03 16:46:49 uyuni-test websockify[1011]: AttributeError: module 'websockify.token_plugins' has no attribute 'JWTTokenApi'
Apr 03 16:46:49 uyuni-test systemd[1]: mgr-websockify.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 16:46:49 uyuni-test systemd[1]: mgr-websockify.service: Unit entered failed state.
Apr 03 16:46:49 uyuni-test systemd[1]: mgr-websockify.service: Failed with result 'exit-code'.
```

The ```mgr-websockify``` service was introduced in c2f8faf09e5e0438c1d9d5f1443374eba51d1a3d.

The ```token_plugin.py``` file is missing the class, that has been introduced upstream in https://github.com/novnc/websockify/commit/f2031eff057cb0a43cdebca9688cdb5706088421

```
uyuni-test:~ # rpm -q --info python3-websockify
Name        : python3-websockify
Version     : 0.8.0
Release     : lp150.1.3
Architecture: noarch
Install Date: Wed Apr  3 09:06:17 2019
Group       : Development/Languages/Python
Size        : 194034
License     : LGPL-3.0 and MPL-2.0 and BSD-2-Clause and BSD-3-Clause
Signature   : RSA/SHA256, Tue Feb 20 00:00:12 2018, Key ID b88b2fd43dbdc284
Source RPM  : python-websockify-0.8.0-lp150.1.3.src.rpm
Build Date  : Mon Oct  2 14:00:00 2017
Build Host  : lamb67
Relocations : (not relocatable)
Packager    : https://bugs.opensuse.org
Vendor      : openSUSE
URL         : https://github.com/kanaka/websockify
Summary     : WebSocket to TCP proxy/bridge
Description :
websockify was formerly named wsproxy and was part of the
noVNC project.

At the most basic level, websockify just translates WebSockets traffic
to normal socket traffic. Websockify accepts the WebSockets handshake,
parses it, and then begins forwarding traffic between the client and
the target in both directions.
Distribution: openSUSE Leap 15.0
uyuni-test:~ #
```

**Comment by admd** [comment]
Closing it. If issue is still valid and need fixing, feel free to reopen it.
