### PR TITLE
Fix custom "mgrcompat.module_run" state function to work with Salt 3005.1

### PR DESCRIPTION
**Pull request by meaksh**
## What does this PR change?

On Salt 3005, the `module.run` state function was refactored and, it was finally decided upstream, that there is no deprecation of legacy syntax for `module.run` happening at all. Both syntax will be supported in future Salt versions.

(See NOTE at the beggining of https://docs.saltproject.io/en/latest/ref/states/all/salt.states.module.html)

In fact, after the refactor done by upstream on 3005 codebase for `module.run` (in order to support both syntaxes), if we tailor our parameters from the old syntax to the new syntax, this would cause issues in the execution of some functions.

Examples:

```
'docker.login' failed: login() got an unexpected keyword argument 'registries'
'cp.push' failed: push() got multiple values for argument 'path'
```

So, this PR simply fixes our custom `mgrcompat.module_run` module to not tailor any parameters (at it is not really needed) in case we are running Salt versions higher than 3004.

(This should be fixing some of the issues we currentely see at HEAD acceptance tests)

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Tracks https://github.com/SUSE/spacewalk/issues/19924

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

### CODE REVIEW

**Review by agraul — CHANGES_REQUESTED** [review]
Given that `module.run` accepts both syntaxes now, I expected that we don't change anything for Salt 3005+ in `mgrcompat.module_run`. Can you clarify why we still run `_tailer_kwargs_to_new_syntax(old_name, **kwargs)`?

**Comment by meaksh** [comment]
Thanks for the quick review! 

Maybe the code is a bit messy, but by default, we are not changing anything for 3005+ - we don't call `_tailor_kwargs_to_new_syntax(old_name, **kwargs)`. But it is true that, in case you place the "use_superseded" config in your minion, then the code will still try to force to the new syntax (which should not really happen).

Let me cover this possible corner case better in the code.

**Comment by meaksh** [comment]
@agraul I think this looks better now

**Comment by agraul** [comment]
> Maybe the code is a bit messy, but by default, we are not changing anything for 3005+ - we don't call `_tailor_kwargs_to_new_syntax(old_name, **kwargs)`.

Are you sure about that? The way I read the code, `use_new_syntax = True` stays `True` for Salt 3005+. The `if use_new_syntax` branch is taken, which calls `_tailor_kwargs_to_new_syntax()`

> But it is true that, in case you explicitely place the "use_superseded" config in your minion, then the code will still try to force to the new syntax (which should not really happen).
>
> Let me cover this possible corner case better in the code.
 

I was only thinking about the default, but if that's also the case we should fix it as well.

**Comment by agraul** [comment]
> @agraul I think this looks better now

Yes, it's better now :+1: . I'd swap the default and get rid of all but one if statement (2016 -- 3004 + use_superseded) to set `use_new_syntax = True` to further simplify the code, but otherwise it's good!

**Comment by meaksh** [comment]
> > @agraul I think this looks better now
> 
> Yes, it's better now +1 . I'd swap the default and get rid of all but one if statement (2016 -- 3004 + use_superseded) to set `use_new_syntax = True` to further simplify the code, but otherwise it's good!

Yeah, this sounds reasonable at this point in time :+1:  - thanks for the suggestion.

I will push some extra changes here.

**Comment by meaksh** [comment]
@agraul suggested changed done :+1:

File: susemanager-utils/susemanager-sls/src/states/mgrcompat.py [hunk 1]
```diff
@@ -50,21 +50,15 @@ def module_run(**kwargs):
...
-    # The new syntax will be used as the default
-    use_new_syntax = True
+    # We use classic "module.run" syntax by default.
+    use_new_syntax = False
 
     if __grains__['saltversioninfo'][0] > 3004:
-        # Only new syntax - default behavior for Phosphorus and future releases
+        # Keep using old syntax - since 3005+ both syntax are supported. Not need of tailoring parameters anymore.
         pass
     elif __grains__['saltversioninfo'][0] > 2016 and 'module.run' in __opts__.get('use_superseded', []):
```
Comment (agraul) [inline susemanager-utils/susemanager-sls/src/states/mgrcompat.py:59]:
```suggestion
   if 2016 < __grains__['saltversioninfo'][0] < 3005 and 'module.run' in __opts__.get('use_superseded', []):
```

**Review by agraul — CHANGES_REQUESTED** [review]
I was proposing to just have one if statement. Without testing, I suggested what I was thinking  of. The first if statement can then be deleted (GitHub didn't let me do a suggestion for both if statements at once).

File: susemanager-utils/susemanager-sls/src/states/mgrcompat.py (hunk 1 above)
Comment (meaksh) [reply susemanager-utils/susemanager-sls/src/states/mgrcompat.py]: Done

**Review by agraul — APPROVED** [review]
Again, haven't tested the code, but it looks good now. Before merging I'd squash the commits since `git log` does not really benefit from the all but the first commit.

**Comment by meaksh** [comment]
I tested this locally and it works fine as expected :+1:
