### PR TITLE
Make "spacecmd" to work with Python 3.12 and higher

### PR DESCRIPTION
**Pull request by meaksh**
## What does this PR change?

This PR fixes `spacecmd` to work with Python 3.12 and higher, fixing the issue importing obsoleted `SafeConfigParser`:

```console
slmicro62:~ # spacecmd
Traceback (most recent call last):
  File "/usr/bin/spacecmd", line 39, in <module>
    from configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib64/python3.13/configparser.py). Did you mean: 'RawConfigParser'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spacecmd", line 41, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: **already covered**

- [x] **DONE**

## Links

Issue(s): #
Port(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

File: spacecmd/src/bin/spacecmd [hunk 1]
```diff
@@ -28,33 +29,44 @@ import logging
...
-    from ConfigParser import SafeConfigParser
+
+try:
+    try:  # python >= 3.12
+        from configparser import ConfigParser
+    except ImportError:  # python 3
+        # pylint: disable-next=deprecated-class
+        from configparser import SafeConfigParser as ConfigParser
+except ImportError:  # python 2
+    from ConfigParser import SafeConfigParser as ConfigParser
```
Comment (agraul) [inline spacecmd/src/bin/spacecmd]: `SafeConfigParser` is an deprecated alias of `ConfigParser` since Python 3.2. We can just use the "new" (14 years old) name for all Python 3 versions.

```suggestion
try:
    from configparser import ConfigParser
except ImportError:  # python 2
    from ConfigParser import SafeConfigParser as ConfigParser
```

**Review by agraul — DISMISSED** [review]
LGTM!

**Review by mcalmer — APPROVED** [review]
